### ISSUE TITLE
Unintended behaviour/error-catching bug when using workflows with IBM backend

### ISSUE THREAD

**Issue by shaohenc** [entropicalabs/openqaoa#105]
### Prerequisites
Before raising this issue, I have already checked that I am:

- [x] running the latest version
- [x] made sure that this issue has not already been filed

### Describe the bug
Using workflows, if the QUBO problem to be compiled contains more qubits than the device chosen, running `q.optimise()` will just pass, without returning an error message.

### To Reproduce
1. Choose an IBM device (eg: `ibm_nairobi` with 6 qubits)
2. Create a QUBO problem requiring more qubits than the device (eg : a 7-qubit MaxCut problem)
3. Run OQ as usual, and finally run `q.optimise()`
4. Cell passes, but it should have failed.

### Expected behavior 
An error message should be thrown to inform the user that the problem and device are incompatible.

**Comment by vishal-ph** [comment]
PR 108 fixes this issue
