### ISSUE TITLE
Error in documentation rendering

### ISSUE THREAD

**Issue by lockwo** [entropicalabs/openqaoa#106]
### Issue Description
On chrome and microsoft edge, the documentation 04 - Working with the QAOA Variational Parameter Classes has the following rendering error: 

![image](https://user-images.githubusercontent.com/42878312/197083160-57717ad3-731a-4602-808a-1b2e8de87bb1.png)

This is on a windows PC.

**Comment by Q-lds** [comment]
Hi @lockwo! Thanks for catching this one! I'll make sure to fix it soon

**Comment by vishal-ph** [comment]
PR 113 fixes this issue
