### ISSUE TITLE
[Feature Request] Custom Mixers

### ISSUE THREAD

**Issue by lockwo** [entropicalabs/openqaoa#112]
The ability to easily use custom mixer's would be nice, currently I see only x and xy supported, but there is a work in exploring more options. The input format could either be a qiskit circuit (depending on internal conversions) or some string based representation, but I think there would be value in this.

**Comment by vishal-ph** [comment]
@lockwo, thanks for the feature request. I agree that having the choice of using more advanced QAOA mixers would be great. For this reason, we have been working on generalizing the ansatz layer of OQ for use with mixers other than `x` and `xy`. This feature is under-review and, hopefully should be available soon!

**Comment by Q-lds** [comment]
The changes or on dev, and will soon make their way to main :)
