### ISSUE TITLE
The names and documentation for the parameters of the .set_classical_optimizer method to be improved

### ISSUE THREAD

**Issue by raulconchello** [entropicalabs/openqaoa#150]
The method `set_classical_optimizer` for the QAOA and RQAOA classes doesn't have the proper documentation. It should be the same as the documentation of the `ClassicalOptimizer` class. The parameters `optimization_progress`, `cost_progress`, `parameter_log`, and `save_intermediate` are missing. Also, these names could be changed to be more descriptive.

**Comment by Q-lds** [comment]
Closing this as it has been dealt by PR153
