### ISSUE TITLE
Resolve IBMQ deprecation warning for Qiskit

### ISSUE THREAD

**Issue by shahidee44** [entropicalabs/openqaoa#184]
### Prerequisites
Before raising this issue, I have already checked that I am:

- [x] running the latest version
- [x] made sure that this issue has not already been filed

### Describe the bug
![image](https://user-images.githubusercontent.com/36878360/219530165-29d4dc25-c435-4ed5-88c6-0a9c3dc50b74.png)

### To Reproduce
The IBMQ import in qiskit is going to be deprecated.

### Additional context
Need to change the way the module is imported. Need to check if setup needs to be changed to accomandate possible module that might not be installed with the package.

**Comment by vishal-ph** [comment]
fixed with PR #217
