### ISSUE TITLE
Implement `as_matrix` method for the `Hamiltonian` class

### ISSUE THREAD

**Issue by vishal-ph** [entropicalabs/openqaoa#232]
### Prerequisites
Before raising this feature request, I made sure:

- [x] It does not lead to duplication.
- [x] It has not already been requested.

### Is your feature request related to a problem? Please describe.
The class `Hamiltonian` in OpenQAOA defined in `src/openqaoa-src/openqaoa/qaoa_components/ansatz_constructor/operators.py` is responsible for constructing the `Cost` and `Mixer` Hamiltonians in QAOA. It fundamentally describes the Hamiltonian object via list of `PauliOp`s defined on a set of qubits and a corresponding list of their coefficients. Implicitly, the definition of the Hamiltonian is then assumed as follows: $$H = \sum_i \alpha_{i} P_i + \sum_{ij} J_{ij} P_{ij},$$ where $\ P_i, P_{ij}$ are one-qubit and two-qubit `PauliOp`s respectively. 

Implement a method in this class that returns the matrix representation of the `Hamiltonian` object. This will be a $2^n x 2^n$ dimensional sum over all Pauli entries as shown above. 

### Describe the solution you'd like
- Implement the method
- Use numpy sparse matrix where relevant
- Implement checks preventing users from creating matrices beyond 20 qubits to prevent memory overflow
- Bonus task: If the Hamiltonian can be expressed as a sparse matrix, shift the qubit restriction to a higher number depending on the sparsity of the matrix

```{python}
class Hamiltonian:
    def as_matrix(self):
        "Implements a numpy array (sparse where relevant) representation
         of the Hamiltonian object."
        #TODO
        return mat
```

**Comment by manulpatel** [comment]
Hello @vishal-ph! I am new to OpenQAOA and woud like to implement this functionality. Could you please assign it to me and if possible show any relavant literature to show matrix rep?

**Comment by vishal-ph** [comment]
@manulpatel, the Hamiltonian object in OpenQAOA is a sum over the terms of the Pauli and Identity operators set tensored over n-qubits. The goal is to represent the sum of these terms in a matrix form. To get started, you may want to start looking at the matrix representation of the Pauli operators here https://en.wikipedia.org/wiki/Pauli_matrices and think about their tensor products.

**Comment by vishal-ph** [comment]
@AlexisRalli, thanks for your contribution to OpenQAOA and helping close this issue!

**Comment by natestemen** [comment]
@AlexisRalli don't forget to comment here on this issue so that you can be assigned to the issue!

**Comment by AlexisRalli** [comment]
Thanks for integrating the code!
