### ISSUE TITLE
Prevent double authentication while using `openqaoa-azure`

### ISSUE THREAD

**Issue by vishal-ph** [entropicalabs/openqaoa#233]
### Prerequisites
Before raising this issue, I have already checked that I am:

- [x] running the latest version
- [x] made sure that this issue has not already been filed

### Describe the bug
Running a QAOA problem using the OpenQAOA workflow as described in [this](https://github.com/entropicalabs/openqaoa/blob/main/examples/12_testing_azure.ipynb) notebook will require web authentication twice before executing the run. For reference, see the attached screenshot.

This happens because DeviceAzure, which is defined in `src/openqaoa-azure/openqaoa_azure/backends/devices.py`, has a method called `check_connection`, that is called twice, once from within the workflow and the other time from within the backend object. 

### To Reproduce
1. Create the Azure device object
2. Create a `qubo` for a problem of choice
3. Initialize the QAOA workflow as `q = QAOA()`
4. Call the compile method and pass the QUBO via `q.compile(qubo)`

### Expected behavior 
Upon executing the above steps, the web authenticator should only prompt once for device authentication

### Screenshots
![image](https://github.com/entropicalabs/openqaoa/assets/35625965/98a1e761-cbb5-46c1-9769-bd5920399f0f)

**Comment by WingCode** [comment]
@vishal-ph I would like to take a stab at this issue. Could you assign it to me?

**Comment by vishal-ph** [comment]
NOTE: - Please branch out from openqaoa/dev and will make the PR into openqaoa/dev. Thanks

**Comment by vishal-ph** [comment]
@TerraVenil, thanks for taking a look at this issue! Regarding your questions:
- Judging from your screenshot, it seems your CLI is not set up with Azure credentials. To access the devices from Azure and use them with OpenQAOA, you must first set up Azure CLI. Instructions to do that can be found [here](https://openqaoa.entropicalabs.com/devices/azure-quantum/#how-to-connect-to-azure-quantum). In case, the issue is something else, please let me know!
- For the second part of your question, you can look [here](https://github.com/entropicalabs/openqaoa/blob/137d3f0a10391adce5bb23cf7536f2d221defb79/src/openqaoa-azure/backends/devices.py#LL59C59-L59C59) and notice that the `check_connection` method of the device object verifies if connections to both `provider` and `QPU` are made, and returns `True` if both `self.provider_connected` and `self.qpu_connected` are True, or if `self.provider_connected` is True and `self.device_name == ""`
As you rightly pointed out, the `check_connection` is in the `qaoa_workflow.py` and `basebackend.py`. However, I think we can add conditionals, in the backend file that first check whether the `device.provider_connected` and `device.qpu_connected` are already `True` and skip `check_connection` if that's the case. 

Let me know if you still have questions or something is unclear! Thanks

**Comment by vishal-ph** [comment]
Fixed this issue in PR #249
