### ISSUE TITLE
Expose brute force solver through OpenQAOA workflows

### ISSUE THREAD

**Issue by vishal-ph** [entropicalabs/openqaoa#234]
### Prerequisites
Before raising this feature request, I made sure:

- [x] It does not lead to duplication.
- [x] It has not already been requested.

### Is your feature request related to a problem? Please describe.
OpenQAOA has a function called `ground_state_hamiltonian` that takes as input the Cost Hamiltonian corresponding to the QUBO problem and outputs the degenerate solutions (or ground states of the Hamiltonian) along with the lowest energy (i.e. ground state energy). The function is defined in `src/openqaoa-core/openqaoa/utilities.py`.

Expose this function as a `QAOA` workflow class method so users can easily access it. 

### Describe the solution you'd like
- Implement the method that calls this function from within the QAOA workflow class
- Make sure to impose an artificial limit on the size of problem (in terms of the number of qubits) to prevent memory overflow.

Ideal workflow
1. `q = QAOA()`
2. `q.compile(qubo)`
3. `q.solve_brute_force()`

### Describe alternatives you've considered
The existing way to obtain the brute force solution of a qubo is described as follows:
1. construct the problem `qubo` 
2. `from openqaoa.utilities import ground_state_hamiltonian
3. Construct the hamiltonian object by calling `prob_hamiltonian = qubo.hamiltonian`
4. Obtain the solution `solution, energy = ground_state_hamiltonian(prob_hamiltonian)`

**Comment by lumapools** [comment]
Hi, I have attempted to implement the `brute_force` method, could you please assign me to this issue? I am just having issues writing a test (in `test_workflows.py`) for the method because the imported modules are from pip. So I am not sure if I should include a test case or not.

**Comment by vishal-ph** [comment]
@lumapools, just did! Thanks

**Comment by lumapools** [comment]
Thank you! Just created the PR with the feature and new tests to be added

**Comment by lumapools** [comment]
I think it is a good idea too! How should we go about merging ? Should we first merge @GiacomoFrn 's PR and then I modify my PR (or close it to create a new one) to only include the (new) tests for @GiacomoFrn code ?

**Comment by Q-lds** [comment]
Perfect! 

@vishal-ph I think we follow @lumapools suggestion. What do you think?

**Comment by vishal-ph** [comment]
thanks @lumapools, @GiacomoFrn for contributing to OpenQAOA and helping solve this issue!

**Comment by GiacomoFrn** [comment]
@vishal-ph , @Q-lds  I believe I also should be assigned to the issue in order to follow the regulation of the unitaryHack and get part of the bounty

**Comment by Q-lds** [comment]
@GiacomoFrn I have added you as well. Hope this fixes it! :)
