### ISSUE TITLE
Add result statistics on measurement outcomes in QAOAResult object

### ISSUE THREAD

**Issue by vishal-ph** [entropicalabs/openqaoa#235]
### Prerequisites

- [x] It does not lead to duplication.
- [x] It has not already been requested.

### Is your feature request related to a problem? Please describe.

The QAOAResult object stores information regarding the QAOA optimization routine. This result object can be accessed post optimization through the `QAOA` workflow object via the following steps:
1. Define the problem `qubo`
2. Initialize QAOA workflow object `q = QAOA()`
3. Set QAOA properties via setter methods
4. Compile the object `q.compile(qubo)`
5. Run the optimization `q.optimize()`
6. Obtain the results of optimization as `qaoa_result = q.result`

Add a method under the `QAOAResult` class that computes some statistical quantities for the measurement outcomes.

### Describe the solution you'd like
The QAOA object can store measurement outcomes (i.e. counts) from each circuit evaluation in the `QAOAResult` object.

- The method sorts the measurement outcomes (a dictionary) in the descending order of counts. 
- It computes the `mean` and `standard deviation` for the optimized set of measurement outcomes. 
- The function also optionally computes these quantities for all intermediate measurement outcomes during optimization if the user specifies. 
- The method should raise an error if the user requires statistics on all intermediate measurement outcomes but hasn't specified saving them during optimization.

### Additional context
An approach adding statistical tools to understand QAOA results better

**Comment by WingCode** [comment]
@vishal-ph I would like to take a stab at this issue. Could you assign it to me?

**Comment by vishal-ph** [comment]
@WingCode, sure! Thanks!

**Comment by Q-lds** [comment]
@TerraVenil, thanks for your contribution! :)
