### ISSUE TITLE
Update `openqaoa-qiskit` to Qiskit 1.0

### ISSUE THREAD

**Issue by KilianPoirier** [entropicalabs/openqaoa#304]
### Issue Description

OpenQAOA is currently not compatible with the latest major release of Qiskit 1.0 and above, for more details see [Qiskit release notes](https://docs.quantum.ibm.com/api/qiskit/release-notes/1.0).

It is important that we update the package requirements and migrate to this new release before the anterior version becomes obsolete and support from the IBM backends stop for older versions of the package.

This issue concerns mostly the Qiskit plugin (`openqaoa-qiskit`) but also has implications on the Azure plugin (`openqaoa-azure`) because of its dependencies.

### Changes to be made

- Update Qiskit dependencies in `openqaoa-qiskit` to be compatible with the latest major release. More details can be found in the [release notes](https://docs.quantum.ibm.com/api/qiskit/release-notes/1.0) and the [migration guide](https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0-installation) provided by IBM. Changes include:
    - Repackaging of the `qiskit` package. `qiskit-terra` has been removed and the core of the package is now located in `qiskit` itself. `qiskit-aer` now has to be imported on its own.
    - Update of the primitives features.
    - QASM conversion methods have been removed.
- Update Qiskit dependencies in `openqaoa-azure` if needed. Currently the version of Qiskit in the Azure quantum package is limited to `<1.0` but it may be updated in the near future.

**Comment by prakharb10** [comment]
Submitted #312 as a possible fix
