### ISSUE TITLE
Update the package to support `python >=3.11`

### ISSUE THREAD

**Issue by KilianPoirier** [entropicalabs/openqaoa#307]
### Issue Description
OpenQAOA currently only supports `python>=3.8, <3.11`. Updating the python version requirements would improve performances (10-60% faster for python 3.11).

### Changes to be made
Update the python version and fix the installation requirements. 

At the moment, the main change is the removal of `setuptools` in the default creation of a new virtual environment.

The files that should be impacted are:
- Requirements of the core package `src/openqaoa-core/requirements.txt`
- Setup of the GitHub workflows `.github/workflows/`

**Comment by rodolfocarobene** [comment]
Hi! I would like to work on this issue :-)

**Comment by KilianPoirier** [comment]
Sure @rodolfocarobene please go ahead!

**Comment by rodolfocarobene** [comment]
Thanks @KilianPoirier ! Could we please close this issue? I think this is required for the Hackaton. Indeed it results still not "resolved" (https://unitaryhack.dev/bounties/)

_Originally posted by @rodolfocarobene in https://github.com/entropicalabs/openqaoa/issues/311#issuecomment-2157561215_
