### ISSUE TITLE
Method to get exact solution?

### ISSUE THREAD

**Issue by lockwo** [entropicalabs/openqaoa#47]
Is there a built in way to get the actual/exact/true solution to a given problem? Obviously it doesn't scale, but I would like to evaluate how well the QAOA is performing.

**Comment by vishal-ph** [comment]
Update: One can now convert a docplex qubo into an equivalent Ising Hamiltonian supported by OQ

**Comment by Q-lds** [comment]
@vishal-ph I think this now is included in the latest release, right?
